// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Sam-Stranding/SamMall/src/adaptor/repo/model"
)

func newLessonLearnRecord(db *gorm.DB, opts ...gen.DOOption) lessonLearnRecord {
	_lessonLearnRecord := lessonLearnRecord{}

	_lessonLearnRecord.lessonLearnRecordDo.UseDB(db, opts...)
	_lessonLearnRecord.lessonLearnRecordDo.UseModel(&model.LessonLearnRecord{})

	tableName := _lessonLearnRecord.lessonLearnRecordDo.TableName()
	_lessonLearnRecord.ALL = field.NewAsterisk(tableName)
	_lessonLearnRecord.ID = field.NewInt64(tableName, "id")
	_lessonLearnRecord.CourseID = field.NewInt64(tableName, "course_id")
	_lessonLearnRecord.LessonID = field.NewInt64(tableName, "lesson_id")
	_lessonLearnRecord.FirstCategoryID = field.NewInt64(tableName, "first_category_id")
	_lessonLearnRecord.SecondCategoryID = field.NewInt64(tableName, "second_category_id")
	_lessonLearnRecord.EntryTime = field.NewTime(tableName, "entry_time")
	_lessonLearnRecord.ExitTime = field.NewTime(tableName, "exit_time")
	_lessonLearnRecord.Duration = field.NewInt64(tableName, "duration")
	_lessonLearnRecord.LastType = field.NewInt32(tableName, "last_type")
	_lessonLearnRecord.UserID = field.NewInt64(tableName, "user_id")

	_lessonLearnRecord.fillFieldMap()

	return _lessonLearnRecord
}

// lessonLearnRecord 课程下课时学习记录表
type lessonLearnRecord struct {
	lessonLearnRecordDo lessonLearnRecordDo

	ALL              field.Asterisk
	ID               field.Int64
	CourseID         field.Int64 // 课程ID
	LessonID         field.Int64 // 课时ID
	FirstCategoryID  field.Int64 // 第一级目录id
	SecondCategoryID field.Int64 // 第二级目录id
	EntryTime        field.Time  // 进入学习时间
	ExitTime         field.Time  // 退出学习时间
	Duration         field.Int64 // 本次学习观看时长
	LastType         field.Int32
	UserID           field.Int64

	fieldMap map[string]field.Expr
}

func (l lessonLearnRecord) Table(newTableName string) *lessonLearnRecord {
	l.lessonLearnRecordDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lessonLearnRecord) As(alias string) *lessonLearnRecord {
	l.lessonLearnRecordDo.DO = *(l.lessonLearnRecordDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lessonLearnRecord) updateTableName(table string) *lessonLearnRecord {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.CourseID = field.NewInt64(table, "course_id")
	l.LessonID = field.NewInt64(table, "lesson_id")
	l.FirstCategoryID = field.NewInt64(table, "first_category_id")
	l.SecondCategoryID = field.NewInt64(table, "second_category_id")
	l.EntryTime = field.NewTime(table, "entry_time")
	l.ExitTime = field.NewTime(table, "exit_time")
	l.Duration = field.NewInt64(table, "duration")
	l.LastType = field.NewInt32(table, "last_type")
	l.UserID = field.NewInt64(table, "user_id")

	l.fillFieldMap()

	return l
}

func (l *lessonLearnRecord) WithContext(ctx context.Context) *lessonLearnRecordDo {
	return l.lessonLearnRecordDo.WithContext(ctx)
}

func (l lessonLearnRecord) TableName() string { return l.lessonLearnRecordDo.TableName() }

func (l lessonLearnRecord) Alias() string { return l.lessonLearnRecordDo.Alias() }

func (l lessonLearnRecord) Columns(cols ...field.Expr) gen.Columns {
	return l.lessonLearnRecordDo.Columns(cols...)
}

func (l *lessonLearnRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lessonLearnRecord) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 10)
	l.fieldMap["id"] = l.ID
	l.fieldMap["course_id"] = l.CourseID
	l.fieldMap["lesson_id"] = l.LessonID
	l.fieldMap["first_category_id"] = l.FirstCategoryID
	l.fieldMap["second_category_id"] = l.SecondCategoryID
	l.fieldMap["entry_time"] = l.EntryTime
	l.fieldMap["exit_time"] = l.ExitTime
	l.fieldMap["duration"] = l.Duration
	l.fieldMap["last_type"] = l.LastType
	l.fieldMap["user_id"] = l.UserID
}

func (l lessonLearnRecord) clone(db *gorm.DB) lessonLearnRecord {
	l.lessonLearnRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lessonLearnRecord) replaceDB(db *gorm.DB) lessonLearnRecord {
	l.lessonLearnRecordDo.ReplaceDB(db)
	return l
}

type lessonLearnRecordDo struct{ gen.DO }

func (l lessonLearnRecordDo) Debug() *lessonLearnRecordDo {
	return l.withDO(l.DO.Debug())
}

func (l lessonLearnRecordDo) WithContext(ctx context.Context) *lessonLearnRecordDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lessonLearnRecordDo) ReadDB() *lessonLearnRecordDo {
	return l.Clauses(dbresolver.Read)
}

func (l lessonLearnRecordDo) WriteDB() *lessonLearnRecordDo {
	return l.Clauses(dbresolver.Write)
}

func (l lessonLearnRecordDo) Session(config *gorm.Session) *lessonLearnRecordDo {
	return l.withDO(l.DO.Session(config))
}

func (l lessonLearnRecordDo) Clauses(conds ...clause.Expression) *lessonLearnRecordDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lessonLearnRecordDo) Returning(value interface{}, columns ...string) *lessonLearnRecordDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lessonLearnRecordDo) Not(conds ...gen.Condition) *lessonLearnRecordDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lessonLearnRecordDo) Or(conds ...gen.Condition) *lessonLearnRecordDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lessonLearnRecordDo) Select(conds ...field.Expr) *lessonLearnRecordDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lessonLearnRecordDo) Where(conds ...gen.Condition) *lessonLearnRecordDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lessonLearnRecordDo) Order(conds ...field.Expr) *lessonLearnRecordDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lessonLearnRecordDo) Distinct(cols ...field.Expr) *lessonLearnRecordDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lessonLearnRecordDo) Omit(cols ...field.Expr) *lessonLearnRecordDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lessonLearnRecordDo) Join(table schema.Tabler, on ...field.Expr) *lessonLearnRecordDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lessonLearnRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *lessonLearnRecordDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lessonLearnRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) *lessonLearnRecordDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lessonLearnRecordDo) Group(cols ...field.Expr) *lessonLearnRecordDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lessonLearnRecordDo) Having(conds ...gen.Condition) *lessonLearnRecordDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lessonLearnRecordDo) Limit(limit int) *lessonLearnRecordDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lessonLearnRecordDo) Offset(offset int) *lessonLearnRecordDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lessonLearnRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *lessonLearnRecordDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lessonLearnRecordDo) Unscoped() *lessonLearnRecordDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lessonLearnRecordDo) Create(values ...*model.LessonLearnRecord) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lessonLearnRecordDo) CreateInBatches(values []*model.LessonLearnRecord, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lessonLearnRecordDo) Save(values ...*model.LessonLearnRecord) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lessonLearnRecordDo) First() (*model.LessonLearnRecord, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonLearnRecord), nil
	}
}

func (l lessonLearnRecordDo) Take() (*model.LessonLearnRecord, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonLearnRecord), nil
	}
}

func (l lessonLearnRecordDo) Last() (*model.LessonLearnRecord, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonLearnRecord), nil
	}
}

func (l lessonLearnRecordDo) Find() ([]*model.LessonLearnRecord, error) {
	result, err := l.DO.Find()
	return result.([]*model.LessonLearnRecord), err
}

func (l lessonLearnRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LessonLearnRecord, err error) {
	buf := make([]*model.LessonLearnRecord, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lessonLearnRecordDo) FindInBatches(result *[]*model.LessonLearnRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lessonLearnRecordDo) Attrs(attrs ...field.AssignExpr) *lessonLearnRecordDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lessonLearnRecordDo) Assign(attrs ...field.AssignExpr) *lessonLearnRecordDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lessonLearnRecordDo) Joins(fields ...field.RelationField) *lessonLearnRecordDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lessonLearnRecordDo) Preload(fields ...field.RelationField) *lessonLearnRecordDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lessonLearnRecordDo) FirstOrInit() (*model.LessonLearnRecord, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonLearnRecord), nil
	}
}

func (l lessonLearnRecordDo) FirstOrCreate() (*model.LessonLearnRecord, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonLearnRecord), nil
	}
}

func (l lessonLearnRecordDo) FindByPage(offset int, limit int) (result []*model.LessonLearnRecord, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lessonLearnRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lessonLearnRecordDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lessonLearnRecordDo) Delete(models ...*model.LessonLearnRecord) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lessonLearnRecordDo) withDO(do gen.Dao) *lessonLearnRecordDo {
	l.DO = *do.(*gen.DO)
	return l
}
