// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Sam-Stranding/SamMall/src/adaptor/repo/model"
)

func newLessonLearnProgress(db *gorm.DB, opts ...gen.DOOption) lessonLearnProgress {
	_lessonLearnProgress := lessonLearnProgress{}

	_lessonLearnProgress.lessonLearnProgressDo.UseDB(db, opts...)
	_lessonLearnProgress.lessonLearnProgressDo.UseModel(&model.LessonLearnProgress{})

	tableName := _lessonLearnProgress.lessonLearnProgressDo.TableName()
	_lessonLearnProgress.ALL = field.NewAsterisk(tableName)
	_lessonLearnProgress.ID = field.NewInt64(tableName, "id")
	_lessonLearnProgress.CourseID = field.NewInt64(tableName, "course_id")
	_lessonLearnProgress.LessonID = field.NewInt64(tableName, "lesson_id")
	_lessonLearnProgress.UserID = field.NewInt64(tableName, "user_id")
	_lessonLearnProgress.PlayPosition = field.NewInt64(tableName, "play_position")
	_lessonLearnProgress.LearnStatus = field.NewInt32(tableName, "learn_status")
	_lessonLearnProgress.CreateAt = field.NewTime(tableName, "create_at")
	_lessonLearnProgress.UpdateAt = field.NewTime(tableName, "update_at")

	_lessonLearnProgress.fillFieldMap()

	return _lessonLearnProgress
}

// lessonLearnProgress 课程下课时学习进度表
type lessonLearnProgress struct {
	lessonLearnProgressDo lessonLearnProgressDo

	ALL          field.Asterisk
	ID           field.Int64
	CourseID     field.Int64
	LessonID     field.Int64
	UserID       field.Int64
	PlayPosition field.Int64 // 视频进度条位置
	LearnStatus  field.Int32 // 1: 学习中  2：已学完
	CreateAt     field.Time
	UpdateAt     field.Time

	fieldMap map[string]field.Expr
}

func (l lessonLearnProgress) Table(newTableName string) *lessonLearnProgress {
	l.lessonLearnProgressDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lessonLearnProgress) As(alias string) *lessonLearnProgress {
	l.lessonLearnProgressDo.DO = *(l.lessonLearnProgressDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lessonLearnProgress) updateTableName(table string) *lessonLearnProgress {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.CourseID = field.NewInt64(table, "course_id")
	l.LessonID = field.NewInt64(table, "lesson_id")
	l.UserID = field.NewInt64(table, "user_id")
	l.PlayPosition = field.NewInt64(table, "play_position")
	l.LearnStatus = field.NewInt32(table, "learn_status")
	l.CreateAt = field.NewTime(table, "create_at")
	l.UpdateAt = field.NewTime(table, "update_at")

	l.fillFieldMap()

	return l
}

func (l *lessonLearnProgress) WithContext(ctx context.Context) *lessonLearnProgressDo {
	return l.lessonLearnProgressDo.WithContext(ctx)
}

func (l lessonLearnProgress) TableName() string { return l.lessonLearnProgressDo.TableName() }

func (l lessonLearnProgress) Alias() string { return l.lessonLearnProgressDo.Alias() }

func (l lessonLearnProgress) Columns(cols ...field.Expr) gen.Columns {
	return l.lessonLearnProgressDo.Columns(cols...)
}

func (l *lessonLearnProgress) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lessonLearnProgress) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 8)
	l.fieldMap["id"] = l.ID
	l.fieldMap["course_id"] = l.CourseID
	l.fieldMap["lesson_id"] = l.LessonID
	l.fieldMap["user_id"] = l.UserID
	l.fieldMap["play_position"] = l.PlayPosition
	l.fieldMap["learn_status"] = l.LearnStatus
	l.fieldMap["create_at"] = l.CreateAt
	l.fieldMap["update_at"] = l.UpdateAt
}

func (l lessonLearnProgress) clone(db *gorm.DB) lessonLearnProgress {
	l.lessonLearnProgressDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lessonLearnProgress) replaceDB(db *gorm.DB) lessonLearnProgress {
	l.lessonLearnProgressDo.ReplaceDB(db)
	return l
}

type lessonLearnProgressDo struct{ gen.DO }

func (l lessonLearnProgressDo) Debug() *lessonLearnProgressDo {
	return l.withDO(l.DO.Debug())
}

func (l lessonLearnProgressDo) WithContext(ctx context.Context) *lessonLearnProgressDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lessonLearnProgressDo) ReadDB() *lessonLearnProgressDo {
	return l.Clauses(dbresolver.Read)
}

func (l lessonLearnProgressDo) WriteDB() *lessonLearnProgressDo {
	return l.Clauses(dbresolver.Write)
}

func (l lessonLearnProgressDo) Session(config *gorm.Session) *lessonLearnProgressDo {
	return l.withDO(l.DO.Session(config))
}

func (l lessonLearnProgressDo) Clauses(conds ...clause.Expression) *lessonLearnProgressDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lessonLearnProgressDo) Returning(value interface{}, columns ...string) *lessonLearnProgressDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lessonLearnProgressDo) Not(conds ...gen.Condition) *lessonLearnProgressDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lessonLearnProgressDo) Or(conds ...gen.Condition) *lessonLearnProgressDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lessonLearnProgressDo) Select(conds ...field.Expr) *lessonLearnProgressDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lessonLearnProgressDo) Where(conds ...gen.Condition) *lessonLearnProgressDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lessonLearnProgressDo) Order(conds ...field.Expr) *lessonLearnProgressDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lessonLearnProgressDo) Distinct(cols ...field.Expr) *lessonLearnProgressDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lessonLearnProgressDo) Omit(cols ...field.Expr) *lessonLearnProgressDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lessonLearnProgressDo) Join(table schema.Tabler, on ...field.Expr) *lessonLearnProgressDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lessonLearnProgressDo) LeftJoin(table schema.Tabler, on ...field.Expr) *lessonLearnProgressDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lessonLearnProgressDo) RightJoin(table schema.Tabler, on ...field.Expr) *lessonLearnProgressDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lessonLearnProgressDo) Group(cols ...field.Expr) *lessonLearnProgressDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lessonLearnProgressDo) Having(conds ...gen.Condition) *lessonLearnProgressDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lessonLearnProgressDo) Limit(limit int) *lessonLearnProgressDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lessonLearnProgressDo) Offset(offset int) *lessonLearnProgressDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lessonLearnProgressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *lessonLearnProgressDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lessonLearnProgressDo) Unscoped() *lessonLearnProgressDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lessonLearnProgressDo) Create(values ...*model.LessonLearnProgress) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lessonLearnProgressDo) CreateInBatches(values []*model.LessonLearnProgress, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lessonLearnProgressDo) Save(values ...*model.LessonLearnProgress) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lessonLearnProgressDo) First() (*model.LessonLearnProgress, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonLearnProgress), nil
	}
}

func (l lessonLearnProgressDo) Take() (*model.LessonLearnProgress, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonLearnProgress), nil
	}
}

func (l lessonLearnProgressDo) Last() (*model.LessonLearnProgress, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonLearnProgress), nil
	}
}

func (l lessonLearnProgressDo) Find() ([]*model.LessonLearnProgress, error) {
	result, err := l.DO.Find()
	return result.([]*model.LessonLearnProgress), err
}

func (l lessonLearnProgressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LessonLearnProgress, err error) {
	buf := make([]*model.LessonLearnProgress, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lessonLearnProgressDo) FindInBatches(result *[]*model.LessonLearnProgress, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lessonLearnProgressDo) Attrs(attrs ...field.AssignExpr) *lessonLearnProgressDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lessonLearnProgressDo) Assign(attrs ...field.AssignExpr) *lessonLearnProgressDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lessonLearnProgressDo) Joins(fields ...field.RelationField) *lessonLearnProgressDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lessonLearnProgressDo) Preload(fields ...field.RelationField) *lessonLearnProgressDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lessonLearnProgressDo) FirstOrInit() (*model.LessonLearnProgress, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonLearnProgress), nil
	}
}

func (l lessonLearnProgressDo) FirstOrCreate() (*model.LessonLearnProgress, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonLearnProgress), nil
	}
}

func (l lessonLearnProgressDo) FindByPage(offset int, limit int) (result []*model.LessonLearnProgress, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lessonLearnProgressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lessonLearnProgressDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lessonLearnProgressDo) Delete(models ...*model.LessonLearnProgress) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lessonLearnProgressDo) withDO(do gen.Dao) *lessonLearnProgressDo {
	l.DO = *do.(*gen.DO)
	return l
}
