// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLessonLearnProgress = "lesson_learn_progress"

// LessonLearnProgress 课程下课时学习进度表
type LessonLearnProgress struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CourseID     int64     `gorm:"column:course_id;not null" json:"course_id"`
	LessonID     int64     `gorm:"column:lesson_id;not null" json:"lesson_id"`
	UserID       int64     `gorm:"column:user_id;not null" json:"user_id"`
	PlayPosition int64     `gorm:"column:play_position;not null;comment:视频进度条位置" json:"play_position"`     // 视频进度条位置
	LearnStatus  int32     `gorm:"column:learn_status;not null;comment:1: 学习中  2：已学完" json:"learn_status"` // 1: 学习中  2：已学完
	CreateAt     time.Time `gorm:"column:create_at;not null" json:"create_at"`
	UpdateAt     time.Time `gorm:"column:update_at;not null" json:"update_at"`
}

// TableName LessonLearnProgress's table name
func (*LessonLearnProgress) TableName() string {
	return TableNameLessonLearnProgress
}
