// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLessonLearnRecord = "lesson_learn_record"

// LessonLearnRecord 课程下课时学习记录表
type LessonLearnRecord struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CourseID         int64     `gorm:"column:course_id;not null;comment:课程ID" json:"course_id"`                      // 课程ID
	LessonID         int64     `gorm:"column:lesson_id;not null;comment:课时ID" json:"lesson_id"`                      // 课时ID
	FirstCategoryID  int64     `gorm:"column:first_category_id;not null;comment:第一级目录id" json:"first_category_id"`   // 第一级目录id
	SecondCategoryID int64     `gorm:"column:second_category_id;not null;comment:第二级目录id" json:"second_category_id"` // 第二级目录id
	EntryTime        time.Time `gorm:"column:entry_time;not null;comment:进入学习时间" json:"entry_time"`                  // 进入学习时间
	ExitTime         time.Time `gorm:"column:exit_time;not null;comment:退出学习时间" json:"exit_time"`                    // 退出学习时间
	Duration         int64     `gorm:"column:duration;not null;comment:本次学习观看时长" json:"duration"`                    // 本次学习观看时长
	LastType         int32     `gorm:"column:last_type;not null" json:"last_type"`
	UserID           int64     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName LessonLearnRecord's table name
func (*LessonLearnRecord) TableName() string {
	return TableNameLessonLearnRecord
}
